import { LUSHAURA_MFR, type SeedProduct } from "./types";

const clean = { isCrueltyFree: true, isParabenFree: true, manufacturer: LUSHAURA_MFR, giftWrapAvailable: true } as const;
const fragrance = { ...clean, isVegan: true, categorySlug: "fragrance", hsnCode: "3303" } as const;
const bath = { ...clean, categorySlug: "bath-body", hsnCode: "3304" } as const;

/** Fragrance + bath & body. */
export const bodyProducts: SeedProduct[] = [
  // ─── Fragrance ───────────────────────────────────────────────────────────
  {
    ...fragrance,
    slug: "vetiver-oud-eau-de-parfum",
    sku: "LA-FRG-001",
    name: "Vetiver & Oud Eau de Parfum",
    shortDescription: "A smoky, woody unisex perfume with Tamil Nadu vetiver and Assamese oud.",
    description:
      "Deep, grounding and quietly confident. Top notes of pink pepper and bergamot open onto a heart of smoky vetiver, settling into a base of Assamese oud and leather.\n\nIt's an extrait-strength 22% concentration, so two sprays last well past eight hours.\n\nPresented in a heavy glass flacon with a hand-turned wooden cap.",
    price: 2499,
    mrp: 2999,
    stock: 5,
    tags: ["perfume", "oud", "vetiver", "unisex", "long-lasting"],
    isFeatured: true,
    weightGrams: 380,
    size: "50 ml",
    skinTypes: ["All skin types"],
    keyIngredients: ["Vetiver", "Oud", "Pink Pepper"],
    ingredients: "Alcohol Denat., Parfum (Fragrance), Aqua, Linalool, Limonene, Coumarin, Citronellol, Geraniol.",
    howToUse: "Spray on pulse points — wrists, neck and behind the ears — from about 15 cm away. Don't rub; let it settle.",
    benefits: ["8+ hours of wear", "Extrait-strength 22% concentration", "Unisex woody-smoky signature"],
    occasions: ["Anniversary", "Birthday", "Wedding"],
    recipients: ["For Him", "For Her", "For Couples"],
    shelfLifeMonths: 36,
  },
  {
    ...fragrance,
    slug: "mogra-musk-eau-de-parfum",
    sku: "LA-FRG-002",
    name: "Mogra Musk Eau de Parfum",
    shortDescription: "Fresh mogra buds over a soft white-musk base — a modern take on the gajra.",
    description:
      "Mogra Musk smells like the first gajra of the evening: fresh, green and heady, softened by white musk and a touch of sandalwood.\n\nIt's floral without being heavy, and it stays close to the skin as the day goes on.\n\nOur most-gifted perfume for brides and bridesmaids.",
    price: 2299,
    mrp: 2699,
    stock: 41,
    tags: ["perfume", "mogra", "jasmine", "floral", "bridal"],
    weightGrams: 380,
    size: "50 ml",
    skinTypes: ["All skin types"],
    keyIngredients: ["Mogra", "White Musk", "Sandalwood"],
    ingredients: "Alcohol Denat., Parfum (Fragrance), Aqua, Benzyl Salicylate, Linalool, Benzyl Benzoate, Hydroxycitronellal.",
    howToUse: "Spray on pulse points and hair. Layer with Kokum Butter Body Balm for longer wear.",
    benefits: ["Fresh, true-to-flower mogra", "Soft musky dry-down", "Long-lasting 18% concentration"],
    occasions: ["Wedding", "Birthday", "Anniversary"],
    recipients: ["For Her"],
    shelfLifeMonths: 36,
  },
  {
    ...fragrance,
    slug: "sandalwood-attar-roll-on",
    sku: "LA-FRG-003",
    name: "Mysore Sandalwood Attar Roll-on",
    shortDescription: "An alcohol-free sandalwood attar distilled the traditional deg-bhapka way.",
    description:
      "Made in Kannauj by a family of attar-makers using copper degs and bamboo bhapka pipes — a method unchanged for centuries.\n\nThe sandalwood is creamy, milky and soft, and deepens on skin through the day. Being oil-based and alcohol-free, it's gentle on sensitive skin.\n\nA little goes a long way: one bottle lasts months.",
    price: 899,
    mrp: 999,
    stock: 0,
    tags: ["attar", "ittar", "sandalwood", "alcohol-free", "roll-on"],
    weightGrams: 60,
    size: "8 ml",
    skinTypes: ["All skin types", "Sensitive"],
    keyIngredients: ["Sandalwood"],
    ingredients: "Santalum Album (Sandalwood) Oil, Parfum (Natural Attar Blend), Tocopherol.",
    howToUse: "Roll onto wrists and behind the ears. Warm skin helps the attar open up.",
    benefits: ["Alcohol-free and skin-friendly", "Traditional deg-bhapka distillation", "Travel-size roll-on"],
    occasions: ["Diwali", "Thank You", "Corporate"],
    recipients: ["For Him", "For Parents", "For Colleagues"],
    manufacturer: "Gulab Singh Attar House, Kannauj (for LushAura)",
    shelfLifeMonths: 60,
  },
  {
    ...fragrance,
    slug: "monsoon-mitti-eau-de-toilette",
    sku: "LA-FRG-004",
    name: "Monsoon Mitti Eau de Toilette",
    shortDescription: "The smell of first rain on dry earth, captured with Kannauj mitti attar.",
    description:
      "Petrichor, bottled. Monsoon Mitti is built around mitti attar — distilled from baked clay — with green notes of wet leaves and a soft vetiver base.\n\nIt's light and airy, made for everyday wear and humid afternoons.\n\nA little nostalgic, very Indian and completely unique.",
    price: 1599,
    mrp: 1899,
    stock: 57,
    tags: ["perfume", "petrichor", "mitti", "fresh", "everyday"],
    isNew: true,
    weightGrams: 320,
    size: "50 ml",
    skinTypes: ["All skin types"],
    keyIngredients: ["Mitti Attar", "Vetiver", "Green Tea"],
    ingredients: "Alcohol Denat., Parfum (Fragrance), Aqua, Limonene, Linalool, Citral.",
    howToUse: "Spray generously on skin and clothes. Reapply through the day as needed — it's designed to be light.",
    benefits: ["Fresh, earthy and unique", "Light enough for everyday", "Made with real mitti attar"],
    occasions: ["Birthday", "Self-care", "Thank You"],
    recipients: ["For Him", "For Her", "For Friends"],
    shelfLifeMonths: 36,
  },

  // ─── Bath & Body ─────────────────────────────────────────────────────────
  {
    ...bath,
    slug: "kokum-butter-body-balm",
    sku: "LA-BTH-001",
    name: "Kokum Butter Body Balm",
    shortDescription: "A rich, melt-in balm with Konkan kokum and shea for very dry skin.",
    description:
      "Kokum butter from the Konkan coast is lighter than shea and absorbs beautifully. We whip it with shea butter, cold-pressed coconut oil and a hint of vanilla.\n\nIt melts on contact and leaves skin soft for 24 hours — elbows, heels and hands included.\n\nWaterless, so there are no emulsifiers or preservatives beyond vitamin E.",
    price: 749,
    mrp: 849,
    stock: 81,
    tags: ["body balm", "kokum", "shea butter", "dry skin", "moisturiser"],
    isFeatured: true,
    isVegan: true,
    weightGrams: 190,
    size: "100 g",
    skinTypes: ["Dry", "Normal", "Sensitive"],
    concerns: ["Dryness", "Rough patches"],
    keyIngredients: ["Kokum Butter", "Shea Butter", "Coconut Oil"],
    ingredients:
      "Garcinia Indica (Kokum) Seed Butter, Butyrospermum Parkii (Shea) Butter, Cocos Nucifera (Coconut) Oil, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Vanilla Planifolia Fruit Extract, Tocopherol.",
    howToUse: "Warm a small amount between palms and massage onto damp skin after a bath. Use extra on elbows, knees and heels.",
    benefits: ["24-hour moisture for very dry skin", "Waterless, preservative-free", "Melts in without greasiness"],
    shelfLifeMonths: 18,
  },
  {
    ...bath,
    slug: "rose-hibiscus-hair-oil",
    sku: "LA-BTH-002",
    name: "Rose & Hibiscus Hair Oil",
    shortDescription: "A weekly champi oil with hibiscus, bhringraj and rose to reduce hair fall.",
    description:
      "Sunday champi, the way our nanis did it. Hibiscus flowers and leaves, bhringraj, amla and rose petals are slow-cooked in cold-pressed coconut and sesame oil.\n\nUsed twice a week, it helps reduce hair fall and adds shine from root to tip.\n\nLightly scented with rose — no mineral oil, no synthetic colour.",
    price: 549,
    mrp: 649,
    stock: 109,
    tags: ["hair oil", "hibiscus", "bhringraj", "hair fall", "champi"],
    isBestseller: true,
    isVegan: true,
    weightGrams: 160,
    size: "100 ml",
    skinTypes: ["All skin types"],
    concerns: ["Hair fall", "Dry scalp", "Dull hair"],
    keyIngredients: ["Rose", "Hibiscus", "Bhringraj", "Amla"],
    ingredients:
      "Cocos Nucifera (Coconut) Oil, Sesamum Indicum (Sesame) Seed Oil, Hibiscus Rosa-Sinensis Flower Extract, Eclipta Alba (Bhringraj) Extract, Phyllanthus Emblica (Amla) Fruit Extract, Rosa Damascena Flower Oil, Tocopherol.",
    howToUse: "Warm slightly and massage into scalp for 5 minutes. Leave on for at least an hour, or overnight, then wash with a mild shampoo.",
    benefits: ["Helps reduce hair fall", "Nourishes a dry scalp", "Adds shine and softness", "No mineral oil"],
    shelfLifeMonths: 18,
  },
  {
    ...bath,
    slug: "sandalwood-haldi-bathing-bars",
    sku: "LA-BTH-003",
    name: "Sandalwood & Haldi Bathing Bars (Set of 3)",
    shortDescription: "Cold-process soap bars with sandalwood, turmeric and goat milk.",
    description:
      "These handmade bars are cold-processed and cured for six weeks, so they're mild and long-lasting.\n\nSandalwood and turmeric soothe and brighten, while goat milk keeps skin soft. Each bar is wrapped in handmade paper.\n\nA simple, beautiful stocking filler for hampers.",
    price: 449,
    mrp: 499,
    stock: 96,
    tags: ["soap", "bathing bar", "sandalwood", "haldi", "handmade"],
    weightGrams: 380,
    hsnCode: "3401",
    size: "3 × 100 g",
    skinTypes: ["Normal", "Dry", "Sensitive"],
    concerns: ["Dullness", "Dryness"],
    keyIngredients: ["Sandalwood", "Turmeric", "Goat Milk"],
    ingredients:
      "Sodium Olivate, Sodium Cocoate, Sodium Castorate, Goat Milk, Santalum Album (Sandalwood) Oil, Curcuma Longa (Turmeric) Root Powder, Glycerin, Tocopherol.",
    howToUse: "Lather between wet hands or on a loofah and massage onto skin. Keep on a draining soap dish between uses.",
    benefits: ["Cold-processed and cured for 6 weeks", "Gentle, non-drying lather", "Handmade in small batches"],
    shelfLifeMonths: 24,
  },
  {
    ...bath,
    slug: "coffee-coconut-body-scrub",
    sku: "LA-BTH-004",
    name: "Coorg Coffee & Coconut Body Scrub",
    shortDescription: "An energising scrub with Coorg arabica and coconut sugar for smoother skin.",
    description:
      "We source fresh-ground arabica from a family estate in Coorg and blend it with coconut sugar and virgin coconut oil.\n\nIt buffs away dry, flaky skin and helps improve the look of uneven texture, leaving skin soft and faintly coffee-scented.\n\nUse two or three times a week, especially before an event.",
    price: 649,
    mrp: 749,
    stock: 63,
    tags: ["body scrub", "coffee", "exfoliation", "coconut", "coorg"],
    isVegan: true,
    weightGrams: 260,
    size: "200 g",
    skinTypes: ["Normal", "Oily", "Combination"],
    concerns: ["Rough texture", "Tan", "Dullness"],
    keyIngredients: ["Coffee", "Coconut Oil", "Coconut Sugar"],
    ingredients:
      "Coffea Arabica (Coffee) Seed Powder, Cocos Nucifera (Coconut) Sugar, Cocos Nucifera (Coconut) Oil, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Butyrospermum Parkii (Shea) Butter, Tocopherol.",
    howToUse: "On damp skin, massage a handful in circular motions for 2–3 minutes. Rinse with lukewarm water and pat dry.",
    benefits: ["Buffs away dry, flaky skin", "Energising coffee aroma", "Leaves skin soft, not stripped"],
    shelfLifeMonths: 12,
  },
];
