import { LUSHAURA_MFR, type SeedProduct } from "./types";

const clean = { isVegan: true, isCrueltyFree: true, isParabenFree: true, manufacturer: LUSHAURA_MFR } as const;
const skincare = { ...clean, categorySlug: "skincare", hsnCode: "3304", giftWrapAvailable: true } as const;
const makeup = { ...clean, categorySlug: "makeup", hsnCode: "3304", giftWrapAvailable: true } as const;

/** Skincare + makeup. Fragrance and bath & body live in products-body.ts. */
export const cosmeticProducts: SeedProduct[] = [
  // ─── Skincare ────────────────────────────────────────────────────────────
  {
    ...skincare,
    slug: "kumkumadi-radiance-face-oil",
    sku: "LA-SKN-001",
    name: "Kumkumadi Radiance Face Oil",
    shortDescription: "A 16-herb Ayurvedic night oil with saffron for visibly brighter, even-toned skin.",
    description:
      "Our hero oil follows a classical kumkumadi tailam recipe: Kashmiri saffron, manjistha, red sandalwood and 13 other herbs slow-infused in sesame and almond oil for 21 days.\n\nIt absorbs in minutes and leaves skin soft, never greasy. With nightly use, dark spots and dullness look visibly reduced in 4–6 weeks.\n\nDermatologically tested on Indian skin. Suitable for all skin types, including combination.",
    price: 1499,
    mrp: 1799,
    stock: 88,
    tags: ["face oil", "kumkumadi", "saffron", "ayurveda", "glow", "night care"],
    isFeatured: true,
    isBestseller: true,
    weightGrams: 140,
    size: "30 ml",
    skinTypes: ["All skin types", "Dry", "Normal", "Combination"],
    concerns: ["Dullness", "Pigmentation", "Uneven tone"],
    keyIngredients: ["Kumkumadi", "Saffron", "Sandalwood"],
    ingredients:
      "Sesamum Indicum (Sesame) Seed Oil, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Crocus Sativus (Saffron) Flower Extract, Rubia Cordifolia (Manjistha) Root Extract, Pterocarpus Santalinus (Red Sandalwood) Wood Extract, Nelumbo Nucifera (Lotus) Flower Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Curcuma Longa (Turmeric) Root Extract, Tocopherol, Parfum (Natural).",
    howToUse:
      "At night, warm 3–4 drops between your palms and press gently onto clean, slightly damp skin. Massage upward for a minute. Use daily; follow with sunscreen in the morning.",
    benefits: [
      "Visibly brightens and evens skin tone",
      "Fades the look of dark spots over 4–6 weeks",
      "Deeply nourishes without clogging pores",
      "Classical 16-herb Ayurvedic formula",
    ],
    shelfLifeMonths: 24,
  },
  {
    ...skincare,
    slug: "ubtan-brightening-face-pack",
    sku: "LA-SKN-002",
    name: "Ubtan Brightening Face Pack",
    shortDescription: "A haldi-chandan ubtan with besan and saffron, just like the ones made at home before weddings.",
    description:
      "The pre-wedding haldi ritual, bottled. Our ubtan blends chickpea flour, turmeric, sandalwood, saffron and rose petals into a fine powder.\n\nMix with rose water or curd for a gentle polish that removes tan and leaves skin soft and glowing.\n\nWe use Kasturi turmeric, which doesn't leave a yellow stain.",
    price: 649,
    mrp: 749,
    stock: 116,
    tags: ["ubtan", "face pack", "haldi", "de-tan", "bridal"],
    isBestseller: true,
    weightGrams: 180,
    size: "100 g",
    skinTypes: ["Normal", "Oily", "Combination"],
    concerns: ["Tan", "Dullness", "Uneven texture"],
    keyIngredients: ["Ubtan", "Saffron", "Sandalwood", "Rose"],
    ingredients:
      "Cicer Arietinum (Chickpea) Flour, Curcuma Aromatica (Kasturi Turmeric) Root Powder, Santalum Album (Sandalwood) Powder, Rosa Damascena (Rose) Petal Powder, Crocus Sativus (Saffron) Stigma, Glycyrrhiza Glabra (Licorice) Root Powder, Avena Sativa (Oat) Kernel Flour.",
    howToUse:
      "Mix one teaspoon with rose water or curd to form a smooth paste. Apply evenly on face and neck, leave for 10 minutes and rinse with gentle circular motions. Use 2–3 times a week.",
    benefits: [
      "Removes tan and brightens dull skin",
      "Gently exfoliates without harsh scrubbing",
      "Non-staining Kasturi turmeric",
      "Traditional haldi ritual, no preservatives",
    ],
    shelfLifeMonths: 12,
  },
  {
    ...skincare,
    slug: "niacinamide-rice-water-serum",
    sku: "LA-SKN-003",
    name: "10% Niacinamide & Rice Water Serum",
    shortDescription: "A lightweight serum that controls oil and refines pores, with fermented rice water.",
    description:
      "Built for humid Indian summers and oily T-zones. Ten per cent niacinamide helps regulate sebum and visibly tightens pores, while fermented rice water soothes and brightens.\n\nThe water-light texture layers easily under sunscreen and makeup.\n\nFragrance-free and non-comedogenic.",
    price: 799,
    mrp: 899,
    stock: 102,
    tags: ["serum", "niacinamide", "oily skin", "pores", "rice water"],
    weightGrams: 110,
    size: "30 ml",
    skinTypes: ["Oily", "Combination"],
    concerns: ["Open pores", "Excess oil", "Acne marks"],
    keyIngredients: ["Niacinamide", "Rice Water", "Zinc PCA"],
    ingredients:
      "Aqua, Niacinamide, Oryza Sativa (Rice) Ferment Filtrate, Propanediol, Zinc PCA, Glycerin, Sodium Hyaluronate, Panthenol, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin.",
    howToUse:
      "Apply 2–3 drops to clean skin morning and night, before moisturiser. Always follow with sunscreen during the day.",
    benefits: [
      "Visibly reduces the look of open pores",
      "Controls shine for a matte finish",
      "Fades post-acne marks over time",
    ],
    shelfLifeMonths: 24,
  },
  {
    ...skincare,
    slug: "vitamin-c-amla-day-cream",
    sku: "LA-SKN-004",
    name: "Vitamin C & Amla Day Cream SPF 20",
    shortDescription: "A glow-boosting day cream with stable vitamin C, amla and light sun protection.",
    description:
      "A fuss-free morning moisturiser that brightens and protects. Stable ethyl ascorbic acid and cold-pressed amla deliver a double dose of vitamin C.\n\nIts whipped gel-cream texture sinks in quickly and leaves a soft, dewy finish with no white cast.\n\nSPF 20 is great for indoor days; for long hours outdoors, layer a dedicated sunscreen.",
    price: 899,
    mrp: 1099,
    stock: 67,
    tags: ["day cream", "vitamin c", "amla", "spf", "glow"],
    weightGrams: 130,
    size: "50 g",
    skinTypes: ["Normal", "Combination", "Dry"],
    concerns: ["Dullness", "Sun damage", "Uneven tone"],
    keyIngredients: ["Vitamin C", "Amla", "Hyaluronic Acid"],
    ingredients:
      "Aqua, Glycerin, Ethylhexyl Methoxycinnamate, Caprylic/Capric Triglyceride, 3-O-Ethyl Ascorbic Acid, Phyllanthus Emblica (Amla) Fruit Extract, Sodium Hyaluronate, Cetearyl Alcohol, Squalane, Tocopherol, Phenoxyethanol, Parfum.",
    howToUse:
      "Every morning, apply a pea-sized amount on face and neck after serum. Reapply sunscreen every 2–3 hours if outdoors.",
    benefits: [
      "Boosts radiance with two forms of vitamin C",
      "Lightweight SPF 20 for daily wear",
      "Hydrates with hyaluronic acid",
    ],
    shelfLifeMonths: 18,
  },
  {
    ...skincare,
    slug: "bakuchiol-night-renewal-cream",
    sku: "LA-SKN-005",
    name: "Bakuchiol Night Renewal Cream",
    shortDescription: "A gentle, plant-based retinol alternative that smooths fine lines overnight.",
    description:
      "Bakuchiol, from the seeds of the babchi plant, has been used in Ayurveda for centuries. Research shows it softens fine lines and improves texture like retinol — without the redness or peeling.\n\nWe pair 1% bakuchiol with kokum butter and ceramides for a rich, cushiony night cream.\n\nSafe for sensitive skin and suitable for daily use.",
    price: 1299,
    mrp: 1599,
    stock: 44,
    tags: ["night cream", "bakuchiol", "anti-ageing", "retinol alternative", "sensitive skin"],
    isNew: true,
    weightGrams: 150,
    size: "50 g",
    skinTypes: ["Dry", "Normal", "Sensitive"],
    concerns: ["Fine lines", "Uneven texture", "Dryness"],
    keyIngredients: ["Bakuchiol", "Kokum Butter", "Ceramides"],
    ingredients:
      "Aqua, Garcinia Indica (Kokum) Seed Butter, Caprylic/Capric Triglyceride, Glycerin, Bakuchiol, Cetearyl Olivate, Sorbitan Olivate, Ceramide NP, Squalane, Niacinamide, Tocopherol, Phenoxyethanol, Ethylhexylglycerin.",
    howToUse:
      "At night, massage a pea-sized amount onto clean skin. Can be layered over Kumkumadi Radiance Face Oil on very dry nights.",
    benefits: [
      "Smooths the look of fine lines",
      "Retinol-like results without irritation",
      "Rich overnight nourishment",
      "Pregnancy-safe alternative to retinol",
    ],
    shelfLifeMonths: 18,
  },
  {
    ...skincare,
    slug: "rose-water-hydrating-toner",
    sku: "LA-SKN-006",
    name: "Rose Water Hydrating Toner",
    shortDescription: "Steam-distilled Kannauj rose water with hyaluronic acid for instant hydration.",
    description:
      "Pure gulab jal from Kannauj, steam-distilled from Damask roses, with a touch of hyaluronic acid and glycerin for lasting hydration.\n\nIt's alcohol-free and gentle enough for daily use, even on sensitive skin.\n\nMist it after cleansing, over makeup to set, or whenever your skin needs a refresh.",
    price: 449,
    mrp: 499,
    stock: 120,
    tags: ["toner", "rose water", "gulab jal", "hydration", "mist"],
    weightGrams: 170,
    size: "100 ml",
    skinTypes: ["All skin types", "Sensitive"],
    concerns: ["Dehydration", "Redness"],
    keyIngredients: ["Rose", "Hyaluronic Acid"],
    ingredients:
      "Rosa Damascena (Rose) Flower Water, Glycerin, Sodium Hyaluronate, Aloe Barbadensis Leaf Juice, Panthenol, Sodium Benzoate, Potassium Sorbate.",
    howToUse:
      "Spray 3–4 times on face after cleansing, or soak a cotton pad and sweep across skin. Follow with serum and moisturiser.",
    benefits: ["Instantly hydrates and refreshes", "Alcohol-free and soothing", "Doubles as a makeup setting mist"],
    shelfLifeMonths: 18,
  },
  {
    ...skincare,
    slug: "saffron-under-eye-gel",
    sku: "LA-SKN-007",
    name: "Saffron & Caffeine Under-Eye Gel",
    shortDescription: "A cooling eye gel that depuffs and brightens tired under-eyes.",
    description:
      "For late nights, long screen days and early flights. Caffeine helps depuff, while saffron and liquorice visibly brighten dark circles.\n\nThe cooling metal-tip applicator gives a gentle massage as you apply.\n\nOphthalmologist tested and fragrance-free.",
    price: 699,
    mrp: 799,
    stock: 59,
    tags: ["eye gel", "dark circles", "puffiness", "caffeine", "saffron"],
    weightGrams: 70,
    size: "15 ml",
    skinTypes: ["All skin types", "Sensitive"],
    concerns: ["Dark circles", "Puffiness"],
    keyIngredients: ["Saffron", "Caffeine", "Licorice"],
    ingredients:
      "Aqua, Glycerin, Caffeine, Crocus Sativus (Saffron) Flower Extract, Glycyrrhiza Glabra (Licorice) Root Extract, Niacinamide, Sodium Hyaluronate, Carbomer, Sodium Hydroxide, Phenoxyethanol.",
    howToUse:
      "Morning and night, glide the applicator gently from the inner to the outer corner of the eye. Pat in any excess with your ring finger.",
    benefits: ["Reduces morning puffiness", "Brightens the look of dark circles", "Cooling metal applicator"],
    shelfLifeMonths: 12,
  },

  // ─── Makeup ──────────────────────────────────────────────────────────────
  {
    ...makeup,
    slug: "matte-lipstick-terracotta-nude",
    sku: "LA-MKP-001",
    name: "Matte Lipstick — Terracotta Nude",
    shortDescription: "A warm brown-nude matte that flatters wheatish to deep skin tones.",
    description:
      "Our signature shade. Terracotta Nude is a warm, earthy brown with a hint of rose — the everyday nude that doesn't wash out Indian skin tones.\n\nThe creamy matte formula glides on in one swipe and stays comfortable for up to 8 hours, thanks to shea butter and vitamin E.\n\nComes in a weighted, refillable metal case.",
    price: 599,
    mrp: 699,
    stock: 93,
    tags: ["lipstick", "matte", "nude", "terracotta", "long-wear"],
    isFeatured: true,
    weightGrams: 45,
    size: "4.2 g",
    shade: "Terracotta Nude",
    skinTypes: ["All skin types"],
    concerns: ["Long wear", "Dry lips"],
    keyIngredients: ["Shea Butter", "Vitamin E"],
    ingredients:
      "Isododecane, Dimethicone, Butyrospermum Parkii (Shea) Butter, Candelilla Cera, Kaolin, Silica, Tocopheryl Acetate, Ricinus Communis Seed Oil, May Contain: CI 77491, CI 77492, CI 77499, CI 77891, CI 15850.",
    howToUse: "Start at the centre of your upper lip and follow the contours outward. For a softer look, dab on with a fingertip.",
    benefits: ["Rich colour in a single swipe", "Up to 8 hours of comfortable wear", "Doesn't dry out lips"],
    shelfLifeMonths: 24,
  },
  {
    ...makeup,
    slug: "matte-lipstick-gulmohar-red",
    sku: "LA-MKP-002",
    name: "Matte Lipstick — Gulmohar Red",
    shortDescription: "A bold, blue-based red inspired by gulmohar blossoms in May.",
    description:
      "The red for weddings, sangeets and Friday nights. Gulmohar Red is a vivid true red with a cool undertone that makes teeth look brighter.\n\nSame creamy-matte formula as our Terracotta Nude, with shea butter and vitamin E for all-day comfort.\n\nTransfer-resistant once set.",
    price: 599,
    mrp: 699,
    stock: 71,
    tags: ["lipstick", "matte", "red", "bridal", "long-wear"],
    weightGrams: 45,
    size: "4.2 g",
    shade: "Gulmohar Red",
    skinTypes: ["All skin types"],
    concerns: ["Long wear", "Dry lips"],
    keyIngredients: ["Shea Butter", "Vitamin E"],
    ingredients:
      "Isododecane, Dimethicone, Butyrospermum Parkii (Shea) Butter, Candelilla Cera, Kaolin, Silica, Tocopheryl Acetate, Ricinus Communis Seed Oil, May Contain: CI 15850, CI 45410, CI 77491, CI 77891.",
    howToUse: "Line lips first for a sharper edge, then fill in. Blot once and reapply for maximum staying power.",
    benefits: ["High-impact, true red colour", "Transfer-resistant once set", "Comfortable matte finish"],
    shelfLifeMonths: 24,
  },
  {
    ...makeup,
    slug: "smudge-proof-kajal-midnight-black",
    sku: "LA-MKP-003",
    name: "Smudge-proof Kajal — Midnight Black",
    shortDescription: "An intense black kajal with almond oil and camphor that lasts 12 hours.",
    description:
      "Deep, jet-black colour in one stroke. Our kajal is inspired by the homemade kajal our grandmothers made with ghee and camphor, reformulated to be smudge-proof and waterproof.\n\nAlmond oil and vitamin E keep the waterline comfortable all day.\n\nOphthalmologist tested and safe for contact-lens wearers.",
    price: 349,
    mrp: 399,
    stock: 118,
    tags: ["kajal", "kohl", "eyeliner", "smudge-proof", "waterproof"],
    isBestseller: true,
    weightGrams: 25,
    size: "0.35 g",
    shade: "Midnight Black",
    skinTypes: ["All skin types", "Sensitive"],
    concerns: ["Long wear", "Smudging"],
    keyIngredients: ["Almond Oil", "Camphor", "Vitamin E"],
    ingredients:
      "Cyclopentasiloxane, Trimethylsiloxysilicate, Synthetic Wax, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Camphor, Tocopheryl Acetate, Polyethylene, CI 77499.",
    howToUse: "Glide along the upper and lower waterline. Smudge with a fingertip within 30 seconds for a smoky look — then it sets.",
    benefits: ["12-hour smudge-proof wear", "Waterproof and sweat-proof", "Gentle on sensitive eyes"],
    shelfLifeMonths: 36,
  },
  {
    ...makeup,
    slug: "lip-cheek-tint-pomegranate",
    sku: "LA-MKP-004",
    name: "Lip & Cheek Tint — Pomegranate",
    shortDescription: "A buildable berry tint for lips and cheeks with beetroot and kokum butter.",
    description:
      "One pot, two uses. This sheer, buildable tint gives lips and cheeks a natural just-pinched flush.\n\nMade with beetroot extract, kokum butter and pomegranate seed oil, it melts into skin and never looks cakey.\n\nPerfect for no-makeup days and for travel.",
    price: 499,
    mrp: 549,
    stock: 64,
    tags: ["tint", "blush", "lip balm", "multi-use", "natural"],
    weightGrams: 40,
    size: "8 g",
    shade: "Pomegranate",
    skinTypes: ["All skin types", "Dry"],
    concerns: ["Dullness", "Dry lips"],
    keyIngredients: ["Kokum Butter", "Beetroot", "Pomegranate Oil"],
    ingredients:
      "Ricinus Communis Seed Oil, Garcinia Indica (Kokum) Seed Butter, Cera Alba Substitute (Candelilla Wax), Punica Granatum Seed Oil, Beta Vulgaris (Beetroot) Root Extract, Tocopherol, CI 15850, CI 77491.",
    howToUse: "Dab onto lips and the apples of your cheeks with your fingertip. Blend outward and build up for more colour.",
    benefits: ["Natural flush for lips and cheeks", "Buildable, never cakey", "Nourishes with kokum butter"],
    shelfLifeMonths: 18,
  },
  {
    ...makeup,
    slug: "dewy-skin-tint-warm-honey",
    sku: "LA-MKP-005",
    name: "Dewy Skin Tint SPF 30 — Warm Honey",
    shortDescription: "A sheer, breathable skin tint with SPF 30 that evens tone and adds a healthy glow.",
    description:
      "For the days you want to look like yourself, only fresher. This lightweight tint blurs redness and evens tone while letting your skin show through.\n\nIt's made with niacinamide and hyaluronic acid and has broad-spectrum SPF 30 — so it replaces three steps in your routine.\n\nWarm Honey suits medium skin with golden undertones.",
    price: 1099,
    mrp: 1299,
    stock: 49,
    tags: ["skin tint", "foundation", "spf", "dewy", "no-makeup"],
    isNew: true,
    weightGrams: 90,
    size: "30 ml",
    shade: "Warm Honey",
    skinTypes: ["Normal", "Dry", "Combination"],
    concerns: ["Uneven tone", "Dullness", "Sun damage"],
    keyIngredients: ["Niacinamide", "Hyaluronic Acid"],
    ingredients:
      "Aqua, Cyclopentasiloxane, Zinc Oxide, Ethylhexyl Methoxycinnamate, Glycerin, Niacinamide, Sodium Hyaluronate, Dimethicone Crosspolymer, Phenoxyethanol, CI 77491, CI 77492, CI 77499, CI 77891.",
    howToUse: "Shake well. Dot onto forehead, cheeks and chin and blend with fingers or a damp sponge. Build a second layer where needed.",
    benefits: ["Sheer, natural coverage", "Broad-spectrum SPF 30", "Dewy finish that lasts", "Hydrates with hyaluronic acid"],
    shelfLifeMonths: 18,
  },
];
