import { LUSHAURA_MFR, type SeedProduct } from "./types";

const hamper = { categorySlug: "gift-hampers", hsnCode: "9803", giftWrapAvailable: true } as const;
const personalised = { categorySlug: "personalised-gifts", isPersonalizable: true, giftWrapAvailable: true } as const;
const festive = { categorySlug: "festive-gifts", giftWrapAvailable: true } as const;
const homeFragrance = { categorySlug: "home-fragrance", giftWrapAvailable: true } as const;

export const giftProducts: SeedProduct[] = [
  // ─── Gift Hampers ────────────────────────────────────────────────────────
  {
    ...hamper,
    slug: "diwali-diya-dry-fruit-hamper",
    sku: "LA-HMP-001",
    name: "Diwali Diya & Dry Fruit Hamper",
    shortDescription: "Hand-painted diyas, premium dry fruits and a saffron candle in a keepsake cane basket.",
    description:
      "Our most-loved festive hamper brings together everything that makes Diwali feel like Diwali — warm light, something sweet and a little indulgence.\n\nInside a handwoven cane basket you'll find a pair of hand-painted terracotta diyas, roasted almonds, cashews and Afghan raisins in glass jars, and our Saffron & Sandalwood soy candle.\n\nEach basket is packed by hand in Bengaluru and finished with a handwritten gift note in your words.",
    price: 2499,
    mrp: 2999,
    stock: 64,
    tags: ["diwali", "dry fruits", "diya", "festive hamper", "corporate"],
    isFeatured: true,
    isBestseller: true,
    weightGrams: 1850,
    occasions: ["Diwali", "Corporate", "Housewarming"],
    recipients: ["For Parents", "For Colleagues", "For Couples"],
    whatsInside: [
      "2 hand-painted terracotta diyas",
      "Roasted almonds (150 g)",
      "Whole cashews (150 g)",
      "Afghan raisins (100 g)",
      "Saffron & Sandalwood soy candle (180 g)",
      "Handwoven cane basket",
      "Handwritten gift note",
    ],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 6,
  },
  {
    ...hamper,
    slug: "corporate-thank-you-hamper",
    sku: "LA-HMP-002",
    name: "Corporate Thank-You Hamper",
    shortDescription: "A polished desk-friendly hamper with artisanal tea, cookies and a brass-lidded candle.",
    description:
      "Say thank you to your team, clients or partners with a hamper that feels personal, not promotional.\n\nIt pairs Darjeeling first-flush tea, butter cookies from a Pune bakery, a vetiver soy candle in a brass-lidded tin and a linen-bound notebook — all in a rigid ivory box.\n\nOrdering 25 or more? Write to care@lushaura.in for custom sleeves with your logo and bulk pricing.",
    price: 1899,
    mrp: 2199,
    stock: 110,
    tags: ["corporate", "thank you", "tea", "office gifting", "bulk"],
    isFeatured: true,
    weightGrams: 1400,
    occasions: ["Corporate", "Thank You", "Diwali"],
    recipients: ["For Colleagues", "For Him", "For Her"],
    whatsInside: [
      "Darjeeling first-flush tea (50 g)",
      "Butter cookies (200 g)",
      "Vetiver soy candle in brass-lidded tin",
      "Linen-bound A5 notebook",
      "Rigid ivory gift box",
    ],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 6,
  },
  {
    ...hamper,
    slug: "rakhi-self-care-hamper",
    sku: "LA-HMP-003",
    name: "Rakhi Self-care Hamper",
    shortDescription: "A handmade rakhi with a rose face mist, kokum lip balm and chocolates for your sibling.",
    description:
      "Swap the usual mithai box for something they'll actually use. This Rakhi hamper pairs a handmade silk-thread rakhi with a little self-care kit.\n\nInside: our Rose Water Hydrating Toner, a Kokum Butter lip balm, dark chocolate thins and a roli-chawal packet for the ritual.\n\nShipped in a tamper-proof box so it travels safely across India — and abroad on request.",
    price: 1499,
    mrp: 1799,
    stock: 72,
    tags: ["rakhi", "raksha bandhan", "self-care", "sibling", "sister"],
    isNew: true,
    weightGrams: 900,
    occasions: ["Rakhi", "Self-care"],
    recipients: ["For Her", "For Him", "For Friends"],
    whatsInside: [
      "Handmade silk-thread rakhi",
      "Rose Water Hydrating Toner (100 ml)",
      "Kokum butter lip balm (10 g)",
      "Dark chocolate thins (100 g)",
      "Roli-chawal packet",
    ],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 12,
  },
  {
    ...hamper,
    slug: "wedding-trousseau-beauty-box",
    sku: "LA-HMP-004",
    name: "Wedding Trousseau Beauty Box",
    shortDescription: "A heirloom-style box of our finest skincare and fragrance for the bride-to-be.",
    description:
      "Designed with brides and their families, this trousseau box brings together our finest pre-wedding rituals in one heirloom-style case.\n\nIt includes Kumkumadi Radiance Face Oil, Ubtan Brightening Face Pack, Mogra Musk Eau de Parfum, Kokum Butter Body Balm and a Terracotta Nude matte lipstick, nestled in a silk-lined wooden box she'll keep long after the wedding.\n\nWe recommend ordering at least three weeks before the big day so she can start her ritual early.",
    price: 5999,
    mrp: 7499,
    stock: 3,
    tags: ["wedding", "bridal", "trousseau", "skincare", "luxury"],
    isFeatured: true,
    weightGrams: 2200,
    occasions: ["Wedding", "Anniversary"],
    recipients: ["For Her"],
    whatsInside: [
      "Kumkumadi Radiance Face Oil (30 ml)",
      "Ubtan Brightening Face Pack (100 g)",
      "Mogra Musk Eau de Parfum (50 ml)",
      "Kokum Butter Body Balm (100 g)",
      "Matte Lipstick — Terracotta Nude",
      "Silk-lined sheesham wood box",
    ],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 18,
  },
  {
    ...hamper,
    slug: "housewarming-brass-bloom-hamper",
    sku: "LA-HMP-005",
    name: "Housewarming Brass Bloom Hamper",
    shortDescription: "A brass urli, mogra reed diffuser and marigold toran to bless a new home.",
    description:
      "A griha pravesh gift that stays on display long after the pooja. The centrepiece is a hand-beaten brass urli made by artisans in Moradabad.\n\nIt comes with our Mogra & Jasmine reed diffuser, a fabric marigold toran for the doorway and a box of temple dhoop cones.\n\nPacked in a reusable jute tote with a card that reads 'Welcome home' — or your own message.",
    price: 3299,
    mrp: 3799,
    stock: 26,
    tags: ["housewarming", "griha pravesh", "brass", "home decor", "diffuser"],
    weightGrams: 2600,
    occasions: ["Housewarming", "Diwali", "Wedding"],
    recipients: ["For Couples", "For Parents", "For Friends"],
    whatsInside: [
      "Hand-beaten brass urli (8 inch)",
      "Mogra & Jasmine reed diffuser (100 ml)",
      "Fabric marigold toran",
      "Temple dhoop cones (20 pcs)",
      "Reusable jute tote",
    ],
    manufacturer: LUSHAURA_MFR,
  },
  {
    ...hamper,
    slug: "new-mom-pamper-hamper",
    sku: "LA-HMP-006",
    name: "New Mom Pamper Hamper",
    shortDescription: "Gentle, fragrance-light essentials to help a new mother rest and recharge.",
    description:
      "The first few months are beautiful and exhausting. This hamper is a small reminder for the new mother to take care of herself too.\n\nInside are our Kokum Butter Body Balm, Rose & Hibiscus Hair Oil, a soft cotton mulmul stole and a tin of saunf-ajwain digestive tea.\n\nEverything is fragrance-light and chosen with care for sensitive skin.",
    price: 2199,
    mrp: 2499,
    stock: 38,
    tags: ["new mom", "baby shower", "self-care", "pamper", "godh bharai"],
    isNew: true,
    weightGrams: 1300,
    occasions: ["Self-care", "Birthday", "Thank You"],
    recipients: ["For Her"],
    whatsInside: [
      "Kokum Butter Body Balm (100 g)",
      "Rose & Hibiscus Hair Oil (100 ml)",
      "Cotton mulmul stole",
      "Saunf-ajwain digestive tea (50 g)",
      "Handwritten gift note",
    ],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 12,
  },

  // ─── Personalised Gifts ──────────────────────────────────────────────────
  {
    ...personalised,
    slug: "personalised-brass-name-diya",
    sku: "LA-PRS-001",
    name: "Personalised Brass Name Diya",
    shortDescription: "A solid brass diya hand-engraved with a name or family initials.",
    description:
      "A diya that becomes part of the family. Cast in solid brass and hand-engraved in Moradabad with up to 12 characters — a name, initials or a short date.\n\nIt holds ghee or oil and burns for about two hours per fill. Polish with lemon and salt to keep it glowing for years.\n\nPersonalised pieces ship in 3–4 working days.",
    price: 899,
    mrp: 1099,
    stock: 85,
    tags: ["personalised", "brass", "diya", "engraved", "diwali"],
    isFeatured: true,
    isBestseller: true,
    weightGrams: 350,
    hsnCode: "7418",
    occasions: ["Diwali", "Housewarming", "Wedding"],
    recipients: ["For Parents", "For Couples"],
    manufacturer: "Shree Brassworks, Moradabad (for LushAura)",
  },
  {
    ...personalised,
    slug: "engraved-sheesham-keepsake-box",
    sku: "LA-PRS-002",
    name: "Engraved Sheesham Wood Keepsake Box",
    shortDescription: "A hand-finished sheesham box laser-engraved with a name and date.",
    description:
      "For wedding cards, first letters, baby bangles and everything too precious for a drawer. Each box is cut from seasoned sheesham wood in Jodhpur and finished with food-safe oil.\n\nWe laser-engrave the lid with up to two lines of text. The inside is lined with ivory velvet.\n\nMeasures 20 × 14 × 8 cm. As with all natural wood, grain and tone vary slightly.",
    price: 1299,
    mrp: 1599,
    stock: 4,
    tags: ["personalised", "wooden box", "keepsake", "anniversary", "engraved"],
    weightGrams: 780,
    hsnCode: "4420",
    occasions: ["Anniversary", "Wedding", "Birthday"],
    recipients: ["For Couples", "For Her", "For Parents"],
    manufacturer: "Marwar Woodcraft, Jodhpur (for LushAura)",
  },
  {
    ...personalised,
    slug: "monogrammed-vegan-leather-travel-pouch",
    sku: "LA-PRS-003",
    name: "Monogrammed Vegan Leather Travel Pouch",
    shortDescription: "A structured travel pouch with gold-foil initials, made from cactus-based vegan leather.",
    description:
      "Sized for skincare, chargers or jewellery, this pouch keeps travel essentials tidy. It's made from plant-based vegan leather with a water-resistant lining.\n\nWe hot-foil up to three initials in gold on the front. Choose from tan or deep olive at checkout note.\n\nA thoughtful gift for the frequent flyer in your life.",
    price: 1499,
    mrp: 1899,
    stock: 46,
    tags: ["personalised", "monogram", "travel", "vegan leather", "for him"],
    isNew: true,
    weightGrams: 240,
    hsnCode: "4202",
    occasions: ["Birthday", "Anniversary", "Corporate"],
    recipients: ["For Him", "For Her", "For Colleagues"],
    manufacturer: LUSHAURA_MFR,
  },
  {
    ...personalised,
    slug: "custom-couple-name-candle",
    sku: "LA-PRS-004",
    name: "Custom Couple Name Soy Candle",
    shortDescription: "A rose-and-oud soy candle with both your names hand-lettered on the jar.",
    description:
      "Made for anniversaries, engagements and 'just because'. We hand-pour a rose-and-oud soy candle into a frosted glass jar and letter your names and date on the front.\n\nIt burns cleanly for around 35 hours. The jar makes a lovely planter or pen stand once it's done.\n\nPlease allow 3 working days for lettering.",
    price: 749,
    mrp: 899,
    stock: 58,
    tags: ["personalised", "candle", "couple", "anniversary", "rose"],
    weightGrams: 420,
    hsnCode: "3406",
    occasions: ["Anniversary", "Wedding", "Birthday"],
    recipients: ["For Couples"],
    manufacturer: LUSHAURA_MFR,
  },

  // ─── Festive Gifts ───────────────────────────────────────────────────────
  {
    ...festive,
    slug: "hand-painted-terracotta-diya-set",
    sku: "LA-FST-001",
    name: "Hand-painted Terracotta Diya Set (Set of 6)",
    shortDescription: "Six wheel-thrown terracotta diyas hand-painted by artisans in Kutch.",
    description:
      "Each diya is shaped on the wheel and hand-painted with mirror-work motifs by artisan families in Kutch, so no two are exactly alike.\n\nThey're pre-seasoned to reduce oil seepage and come with cotton wicks for your first lighting.\n\nBy buying these you support a women-led collective we've worked with since 2021.",
    price: 599,
    mrp: 799,
    stock: 120,
    tags: ["diya", "terracotta", "diwali", "handmade", "artisan"],
    isBestseller: true,
    weightGrams: 650,
    hsnCode: "6912",
    occasions: ["Diwali", "Housewarming"],
    recipients: ["For Parents", "For Friends", "For Colleagues"],
    manufacturer: "Kutch Mati Collective, Bhuj (for LushAura)",
  },
  {
    ...festive,
    slug: "rakhi-thali-gift-set",
    sku: "LA-FST-002",
    name: "Rakhi Thali Gift Set",
    shortDescription: "A German-silver thali with two handmade rakhis, kumkum box and diya.",
    description:
      "Everything for the Rakhi ritual in one beautiful set. The German-silver thali is embossed with a paisley border and polished to a soft shine.\n\nIt includes two handmade rakhis, a kumkum-chawal box, a small diya and a pack of mishri.\n\nThe thali can be reused for every festival through the year.",
    price: 1099,
    mrp: 1299,
    stock: 34,
    tags: ["rakhi", "thali", "pooja", "festive", "silver"],
    weightGrams: 700,
    hsnCode: "7114",
    occasions: ["Rakhi", "Diwali"],
    recipients: ["For Him", "For Her"],
    manufacturer: LUSHAURA_MFR,
  },
  {
    ...festive,
    slug: "festive-mithai-tin-box",
    sku: "LA-FST-003",
    name: "Festive Mithai Tin Box",
    shortDescription: "Kaju katli, pista rolls and besan laddoos in a hand-illustrated collectible tin.",
    description:
      "We partnered with a third-generation halwai in Indore for this tin. Inside: kaju katli, pista rolls and ghee-roasted besan laddoos made fresh for every batch.\n\nThe tin is illustrated with a festive bazaar scene by a Kolkata artist and is lovely to keep.\n\nBest enjoyed within 15 days. Ships only within India.",
    price: 849,
    mrp: 849,
    stock: 0,
    tags: ["mithai", "sweets", "diwali", "tin", "kaju katli"],
    weightGrams: 600,
    hsnCode: "1704",
    giftWrapAvailable: false,
    occasions: ["Diwali", "Corporate", "Thank You"],
    recipients: ["For Colleagues", "For Parents", "For Friends"],
    manufacturer: "Annapurna Sweets, Indore (for LushAura)",
    shelfLifeMonths: 1,
  },
  {
    ...festive,
    slug: "brass-urli-floating-candle-set",
    sku: "LA-FST-004",
    name: "Brass Urli & Floating Candle Set",
    shortDescription: "A 10-inch brass urli with 12 rose-scented floating candles.",
    description:
      "Fill it with water, flower petals and floating candles for a centrepiece that lights up any doorway or dining table.\n\nThe urli is hand-beaten brass with a lacquered finish that resists tarnish. The 12 floating candles burn for about 3 hours each.\n\nA popular gift for Diwali, weddings and housewarmings.",
    price: 1799,
    mrp: 2299,
    stock: 22,
    tags: ["urli", "brass", "floating candles", "decor", "diwali"],
    isFeatured: true,
    weightGrams: 1500,
    hsnCode: "7418",
    occasions: ["Diwali", "Housewarming", "Wedding"],
    recipients: ["For Parents", "For Couples"],
    manufacturer: "Shree Brassworks, Moradabad (for LushAura)",
  },

  // ─── Home Fragrance ──────────────────────────────────────────────────────
  {
    ...homeFragrance,
    slug: "saffron-sandalwood-soy-candle",
    sku: "LA-HFR-001",
    name: "Saffron & Sandalwood Soy Candle",
    shortDescription: "A warm, golden soy candle with Kashmiri saffron and Mysore sandalwood notes.",
    description:
      "Our signature scent: warm saffron up top, creamy sandalwood at the heart and a soft amber base. It fills a medium room without being overpowering.\n\nHand-poured in Bengaluru with 100% soy wax and a lead-free cotton wick, in a reusable amber glass jar.\n\nBurn time: approximately 40 hours. Trim the wick to 5 mm before each use.",
    price: 899,
    mrp: 1099,
    stock: 96,
    tags: ["candle", "saffron", "sandalwood", "soy wax", "home fragrance"],
    isFeatured: true,
    isBestseller: true,
    weightGrams: 480,
    size: "180 g",
    hsnCode: "3406",
    keyIngredients: ["Saffron", "Sandalwood"],
    occasions: ["Diwali", "Housewarming", "Birthday", "Self-care"],
    recipients: ["For Her", "For Friends", "For Couples"],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 24,
  },
  {
    ...homeFragrance,
    slug: "mogra-jasmine-reed-diffuser",
    sku: "LA-HFR-002",
    name: "Mogra & Jasmine Reed Diffuser",
    shortDescription: "A flame-free diffuser that smells like a fresh gajra, lasting up to 10 weeks.",
    description:
      "Inspired by the gajra-sellers outside Mylapore temple, this diffuser captures fresh mogra buds with a hint of green leaves.\n\nIt comes with eight rattan reeds; flip them once a week for a stronger throw. One bottle lasts 8–10 weeks.\n\nFlame-free, so it's safe for bedrooms, bathrooms and homes with pets.",
    price: 1199,
    mrp: 1399,
    stock: 52,
    tags: ["diffuser", "mogra", "jasmine", "home fragrance", "flame-free"],
    weightGrams: 520,
    size: "100 ml",
    hsnCode: "3307",
    keyIngredients: ["Mogra", "Jasmine"],
    occasions: ["Housewarming", "Thank You", "Self-care"],
    recipients: ["For Her", "For Parents", "For Friends"],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 24,
  },
  {
    ...homeFragrance,
    slug: "vetiver-khus-room-mist",
    sku: "LA-HFR-003",
    name: "Vetiver & Khus Room Mist",
    shortDescription: "A cooling, earthy room and linen mist that smells like the first summer rain.",
    description:
      "Remember the khus curtains of Indian summers? This mist brings back that cool, earthy calm in a few sprays.\n\nUse it on curtains, pillows and upholstery, or spritz the room before guests arrive. It's water-based and won't stain fabric.\n\nMade with steam-distilled vetiver from Tamil Nadu.",
    price: 549,
    mrp: 649,
    stock: 78,
    tags: ["room spray", "vetiver", "khus", "linen mist", "summer"],
    weightGrams: 260,
    size: "150 ml",
    hsnCode: "3307",
    keyIngredients: ["Vetiver"],
    occasions: ["Housewarming", "Self-care", "Thank You"],
    recipients: ["For Him", "For Friends", "For Colleagues"],
    manufacturer: LUSHAURA_MFR,
    shelfLifeMonths: 24,
  },
  {
    ...homeFragrance,
    slug: "temple-dhoop-cone-gift-box",
    sku: "LA-HFR-004",
    name: "Temple Dhoop Cone Gift Box",
    shortDescription: "Forty low-smoke dhoop cones in guggul, loban and rose, with a brass holder.",
    description:
      "Hand-rolled from cow-dung ash, herbs and natural resins by a women's cooperative near Varanasi.\n\nThe box holds 40 cones across three fragrances — guggul, loban and rose — plus a small brass holder. They're low-smoke and charcoal-free.\n\nLight the tip, let it glow, and blow out the flame. Each cone burns for 15–20 minutes.",
    price: 449,
    mrp: 499,
    stock: 105,
    tags: ["dhoop", "incense", "pooja", "temple", "loban"],
    weightGrams: 300,
    hsnCode: "3307",
    occasions: ["Diwali", "Housewarming", "Thank You"],
    recipients: ["For Parents", "For Colleagues"],
    manufacturer: "Kashi Gram Udyog, Varanasi (for LushAura)",
    shelfLifeMonths: 36,
  },
];
